package br.com.pi_2026_1_etec.view.telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laris
 */
public class TelaQuestao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuestao.class.getName());

    /**
     * Creates new form TelaQuestao
     */
    public TelaQuestao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternativa1 = new javax.swing.JButton();
        Alternativa2 = new javax.swing.JButton();
        Alternativa3 = new javax.swing.JButton();
        Alternativa4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        alternativa1.setBackground(new java.awt.Color(204, 204, 204));
        alternativa1.setText("Alternativa 1");
        alternativa1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255)));
        alternativa1.setFocusPainted(false);
        alternativa1.addActionListener(this::alternativa1ActionPerformed);

        Alternativa2.setBackground(new java.awt.Color(204, 204, 204));
        Alternativa2.setText("Alternativa 2");
        Alternativa2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255)));
        Alternativa2.setFocusPainted(false);
        Alternativa2.addActionListener(this::Alternativa2ActionPerformed);

        Alternativa3.setBackground(new java.awt.Color(204, 204, 204));
        Alternativa3.setText("Alternativa 3");
        Alternativa3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255)));
        Alternativa3.setFocusPainted(false);
        Alternativa3.addActionListener(this::Alternativa3ActionPerformed);

        Alternativa4.setBackground(new java.awt.Color(204, 204, 204));
        Alternativa4.setText("Alternativa 4");
        Alternativa4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), null, new java.awt.Color(153, 153, 153), new java.awt.Color(255, 255, 255)));
        Alternativa4.setFocusPainted(false);
        Alternativa4.addActionListener(this::Alternativa4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(alternativa1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(Alternativa3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alternativa1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alternativa2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alternativa3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Alternativa4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void alternativa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativa1ActionPerformed
        alternativa1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180,180,180), 2, true));
        alternativa1.setBackground(new java.awt.Color(240,240,240));
        alternativa1.setFocusPainted(false);
        alternativa1.setContentAreaFilled(true);
    }//GEN-LAST:event_alternativa1ActionPerformed

    private void Alternativa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa2ActionPerformed
        Alternativa2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180,180,180), 2, true));
    }//GEN-LAST:event_Alternativa2ActionPerformed

    private void Alternativa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa3ActionPerformed
        Alternativa3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180,180,180), 2, true));
    }//GEN-LAST:event_Alternativa3ActionPerformed

    private void Alternativa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alternativa4ActionPerformed
        Alternativa4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180,180,180), 2, true));
    }//GEN-LAST:event_Alternativa4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaQuestao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alternativa2;
    private javax.swing.JButton Alternativa3;
    private javax.swing.JButton Alternativa4;
    private javax.swing.JButton alternativa1;
    // End of variables declaration//GEN-END:variables
}
